"""empty message

Revision ID: 82775bd7fb07
Revises: 71f641dff576
Create Date: 2023-01-25 21:19:39.446973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82775bd7fb07'
down_revision = '71f641dff576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_table('category')
    # ### end Alembic commands ###
